### ISSUE TITLE
Flash__attn_wmma not found

### ISSUE THREAD

**Issue by xCentral** [Repeerc/ComfyUI-flash-attention-rdna3-win-zluda#1]
`Zluda\custom_nodes\ComfyUI-flash-attention-rdna3-win-zluda-main\__init__.py", line 58, in <module>
    from .hip57 import flash_attn_wmma
ImportError: DLL load failed while importing flash_attn_wmma: The specified module could not be found.`

Just wanted to be certain, but to fix this do I just use "pip install flash-attn" in my venv?

**Comment by Repeerc** [comment]
No need to install flash-attn. The .dll and .pyd was built by python 3.10 in windows environment, so need python 3.10 version to load.

**Comment by xCentral** [comment]
Ah, I understand I was trying to use 3.11, Thank you !
